# Load libraries 
require(pacman)
pacman::p_load(tidyverse, sf, fs, rgbif, geodata, rnaturalearthdata, rnaturalearth, 
               dplyr,ggspatial, hrbrthemes, ggthemes, terra, raster, RColorBrewer, 
               geodata, glue)

## Prepare data input
### Load environmental layers 

bio1 <- raster(paste0("raster/wc2.1_2.5m_bio_1.tif"))
bio2 <- raster(paste0("raster/wc2.1_2.5m_bio_2.tif"))
bio3 <- raster(paste0("raster/wc2.1_2.5m_bio_3.tif"))
bio4 <- raster(paste0("raster/wc2.1_2.5m_bio_4.tif"))
bio5 <- raster(paste0("raster/wc2.1_2.5m_bio_5.tif"))
bio6 <- raster(paste0("raster/wc2.1_2.5m_bio_6.tif"))
bio7 <- raster(paste0("raster/wc2.1_2.5m_bio_7.tif"))
bio8 <- raster(paste0("raster/wc2.1_2.5m_bio_8.tif"))
bio9 <- raster(paste0("raster/wc2.1_2.5m_bio_9.tif"))
bio10 <- raster(paste0("raster/wc2.1_2.5m_bio_10.tif"))
bio11 <- raster(paste0("raster/wc2.1_2.5m_bio_11.tif"))
bio12 <- raster(paste0("raster/wc2.1_2.5m_bio_12.tif"))
bio13 <- raster(paste0("raster/wc2.1_2.5m_bio_13.tif"))
bio14 <- raster(paste0("raster/wc2.1_2.5m_bio_14.tif"))
bio15 <- raster(paste0("raster/wc2.1_2.5m_bio_15.tif"))
bio16 <- raster(paste0("raster/wc2.1_2.5m_bio_16.tif"))
bio17 <- raster(paste0("raster/wc2.1_2.5m_bio_17.tif"))
bio18 <- raster(paste0("raster/wc2.1_2.5m_bio_18.tif"))
bio19 <- raster(paste0("raster/wc2.1_2.5m_bio_19.tif"))
elev <- raster(paste0("raster/wc2.1_2.5m_elev.tif"))
PopDen <- raster(paste0("raster/population_density.tif"))
UrbAcc <- raster(paste0("raster/urban_accessibility.tif"))
LC <- raster(paste0("raster/land_cover.tif"))
NDVI <- raster(paste0("raster/veg_index.tif"))

### Projections 

crs(LC) <- "+proj=longlat +ellps=WGS84 +datum=WGS84 +units=m +no_defs"

### Crop rasters

NEA <- read_sf("South_America.shp")

bio1 <- terra::crop(bio1, NEA)
bio2 <- terra::crop(bio2, NEA)
bio3 <- terra::crop(bio3, NEA)
bio4 <- terra::crop(bio4, NEA)
bio5 <- terra::crop(bio5, NEA)
bio6 <- terra::crop(bio6, NEA)
bio7 <- terra::crop(bio7, NEA)
bio8 <- terra::crop(bio8, NEA)
bio9 <- terra::crop(bio9, NEA)
bio10 <- terra::crop(bio10, NEA)
bio11 <- terra::crop(bio11, NEA)
bio12 <- terra::crop(bio12, NEA)
bio13 <- terra::crop(bio13, NEA)
bio14 <- terra::crop(bio14, NEA)
bio15 <- terra::crop(bio15, NEA)
bio16 <- terra::crop(bio16, NEA)
bio17 <- terra::crop(bio17, NEA)
bio18 <- terra::crop(bio18, NEA)
bio19 <- terra::crop(bio19, NEA)
elev <- terra::crop(elev, NEA)
ndvi <- terra::crop(NDVI, NEA)
popden <- terra::crop(PopDen, NEA)
urbacc <- terra::crop(UrbAcc, NEA)
LC <- terra::crop(LC, NEA)

### Resampled to 2.5m

LC <- resample(LC, bio1, method='ngb')
popden <- resample(popden, bio1, method='ngb')
urbacc <- resample(urbacc, bio1, method='ngb')
ndvi <- urbacc <- resample(ndvi, bio1, method='ngb')

### Mask

bio1 <- terra::mask(bio1, NEA)
bio2 <- terra::mask(bio2, NEA)
bio3 <- terra::mask(bio3, NEA)
bio4 <- terra::mask(bio4, NEA)
bio5 <- terra::mask(bio5, NEA)
bio6 <- terra::mask(bio6, NEA)
bio7 <- terra::mask(bio7, NEA)
bio8 <- terra::mask(bio8, NEA)
bio9 <- terra::mask(bio9, NEA)
bio10 <- terra::mask(bio10, NEA)
bio11 <- terra::mask(bio11, NEA)
bio12 <- terra::mask(bio12, NEA)
bio13 <- terra::mask(bio13, NEA)
bio14 <- terra::mask(bio14, NEA)
bio15 <- terra::mask(bio15, NEA)
bio16 <- terra::mask(bio16, NEA)
bio17 <- terra::mask(bio17, NEA)
bio18 <- terra::mask(bio18, NEA)
bio19 <- terra::mask(bio19, NEA)
elev <- terra::mask(elev, NEA)
ndvi <- terra::mask(ndvi, NEA)
popden <- terra::mask(popden, NEA)
urbacc <- terra::mask(urbacc, NEA)
LC <- terra::mask(LC, NEA)

### Write rasters

terra::writeRaster(x = bio1, filename = 'raster/current/bio1.tif')
terra::writeRaster(x = bio2, filename = 'raster/current/bio2.tif')
terra::writeRaster(x = bio3, filename = 'raster/current/bio3.tif')
terra::writeRaster(x = bio4, filename = 'raster/current/bio4.tif')
terra::writeRaster(x = bio5, filename = 'raster/current/bio5.tif')
terra::writeRaster(x = bio6, filename = 'raster/current/bio6.tif')
terra::writeRaster(x = bio7, filename = 'raster/current/bio7.tif')
terra::writeRaster(x = bio8, filename = 'raster/current/bio8.tif')
terra::writeRaster(x = bio9, filename = 'raster/current/bio9.tif')
terra::writeRaster(x = bio10, filename = 'raster/current/bio10.tif')
terra::writeRaster(x = bio11, filename = 'raster/current/bio11.tif')
terra::writeRaster(x = bio12, filename = 'raster/current/bio12.tif')
terra::writeRaster(x = bio13, filename = 'raster/current/bio13.tif')
terra::writeRaster(x = bio14, filename = 'raster/current/bio14.tif')
terra::writeRaster(x = bio15, filename = 'raster/current/bio15.tif')
terra::writeRaster(x = bio16, filename = 'raster/current/bio16.tif')
terra::writeRaster(x = bio17, filename = 'raster/current/bio17.tif')
terra::writeRaster(x = bio18, filename = 'raster/current/bio18.tif')
terra::writeRaster(x = bio19, filename = 'raster/current/bio19.tif')
terra::writeRaster(x = elev, filename = 'raster/current/elevation.tif')
terra::writeRaster(x = ndvi, filename = 'raster/current/ndvi.tif')
terra::writeRaster(x = LC, filename = 'raster/current/land_cover.tif')
terra::writeRaster(x = popden, filename = 'raster/current/populationdensity.tif')
terra::writeRaster(x = urbacc, filename = 'raster/current/urban_accessibility.tif')
